config/routes.rb
Rails.application.routes.draw do
resources :registrations, only: [:new, :create]
resources :logins, only: [:new, :create]
resources :posts, only: [:index, :new, :create, :edit, :update, :show, :destroy]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root"registrations#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
  
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  validates :password, presence: true

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    user = User.find_by(id: session[:user_id])
    redirect_to new_login_path unless user
  end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def new
    user = User.find_by(id: session[:user_id])
    redirect_to posts_path if user
    @user = User.new
  end

  def create
    @user = User.find_by(login_params)
    if @user
      session[:user_id] = @user.id
      redirect_to posts_path
    else
      flash[:alert] = "Email or Password incorrect"
      render :new, status: :unprocessable_entity
    end
  end

  private
  def login_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    user = User.find_by(id: session[:user_id])
    redirect_to new_login_path unless user
    @posts = Post.includes(:user).all
    
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = session[:user_id]

    if @post.save
      redirect_to @post
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @post = Post.find(params[:id])
  end
  

  def edit
    user = User.find_by(id: session[:user_id])
    @post = Post.find(params[:id])

    if user.id != @post.user_id
      flash[:alert] = "Please login to edit your posts"
      redirect_to post_path
    end
  end

  def update
     @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to @post
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    user = User.find_by(id: session[:user_id])
    @post = Post.find(params[:id])
    if user.id != @post.user_id
      flash[:alert] = "Please login to delete your posts"
      redirect_to post_path
    else
      @post.destroy
      redirect_to posts_path
    end
  end

  private

    def post_params
      params.require(:post).permit(:user_id, :title, :body)
    end

end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @user = User.new 
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to new_login_path
    else
      flash[:alert] = "Couldn't save the User!"
      render :new, status: :unprocessable_entity
    end
  end


  private 
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div><%= alert %></div>
    <div><%= notice %></div>
    <%= yield %>
  </body>
</html>

app/views/logins/create.html.erb
<h1>Login#create</h1>
<p>Find me in app/views/login/create.html.erb</p>

app/views/logins/new.html.erb
<h1>Login</h1>

<%= form_with model: @user, url: logins_path do |form| %>
  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>
    <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>
  <div>
    <%= form.submit "Login"%>
  </div>
<% end %>

app/views/posts/_form.html.erb
<%= form_with model: @post do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= post.body %>
  </p>
   <p>
    <strong>Name:</strong>
    <%= post.user.name %>
  </p>
</div>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<h1>Posts</h1>

<ul>
  <% @posts.each do |post| %>    
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</ul>

<%= link_to "Create New Post", new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render "form", post:@post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>